### ISSUE TITLE
Excel Read hadoopoffice

### ISSUE THREAD

**Issue by pkvg** [ZuInnoTe/hadoopoffice#25]
Hi, I am using hadoopoffice in my spark application. I have followed your steps and added the dependency in my pom.xml file.

<dependency>
<groupId>com.github.zuinnote</groupId> 
<artifactId>spark-hadoopoffice-ds_2.11</artifactId>
<version>1.0.4</version> 
</dependency>

when i run my program i receive the below error.

18/02/20 13:13:00 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 3, 192.168.0.5, executor 1): java.lang.NullPointerException
	at org.apache.hadoop.conf.Configuration.<init>(Configuration.java:711)
	at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:436)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.<init>(JobContextImpl.java:67)
	at org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl.<init>(TaskAttemptContextImpl.java:49)
	at org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl.<init>(TaskAttemptContextImpl.java:44)
	at org.zuinnote.spark.office.excel.HadoopFileExcelReader.<init>(HadoopFileExcelReader.scala:53)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$2.apply(DefaultSource.scala:413)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$2.apply(DefaultSource.scala:412)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:138)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:122)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:168)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:124)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I tried with all versions of org.apache.spark. I am unable to move further. Looks like JobConf value is passed as null.

Also which hadoop version is the library referring to JobConf? 

This is really important to me in reading XLS or XLSX file. Appreciate your timely help in fixing this. 

Thanks

**Comment by jornfranke** [comment]
Can you please share more of your source code and the full pom.xml

The datasource is for Spark 2 and there is an example application in the wiki and the example subfolder. Alternatively you can use the hadoopoffice library directly with other versions of Spark.

Please use only the newest version of the library.

**Comment by pkvg** [comment]
Hi, please find the spark code below that I use to read the xlsx file.

Dataset<Row> dsAsRow = sparkSQL.read().format("org.zuinnote.spark.office.excel")
						   .option("hadoopoffice.read.mimeType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
						   .option("io.file.buffer.size", 64)
						   .option("hadoopoffice.read.sheets", SheetName)
						   .option("read.spark.useHeader", useHeader)
						   .option("hadoopoffice.read.lowFootprint", true).load(ProfileSelector.confFileProperties.getProperty("CLUSTER_PATH").trim() + filePath.trim());

The input xlsx file resides in azure blob. "wasb://file path to xlsx" wrapper to hdfs.  Please find the pom dependencies below

<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		
			
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-hive_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-streaming_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		
		
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>[3.1.0,]</version>
			
		</dependency>

		
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.9.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.json</groupId>
			<artifactId>javax.json-api</artifactId>
			<version>1.1.2</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.0</version>
			<scope>provided</scope>
		</dependency>

		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.3.2</version>
		</dependency>

		
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>

		

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-servicebus</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.qpid</groupId>
			<artifactId>qpid-jms-client</artifactId>
			<version>[0.27.0,]</version>
		</dependency>
		<dependency>
			<groupId>org.apache.qpid</groupId>
			<artifactId>proton-j</artifactId>
			<version>[0.23.0,]</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>[1.7.25,]</version>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>[1.4,]</version>
		</dependency>
		<dependency>
			<groupId>com.github.zuinnote</groupId> 
			<artifactId>spark-hadoopoffice-ds_2.11</artifactId>
			<version>1.0.4</version> 
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>6.1.0</version>
		</dependency>
	</dependencies>

I run my application in azure spark hdinsight cluster. Kindly direct me to the right version of the dependent library that I can add to my pom. Earlier I referred to the build.sbt to understand the dependent libraries version used by hadoopoffice and added them to my pom but i had no luck doing so, i still got the above error.

Also the xlsx file has approximate 1.5 million records is expected to grow, having said that how would io.file.buffer.size and hadoopoffice.read.lowFootprint help me to optimize reads i.e  the time taken to read. I also understand that reading xlsx file has memory footprint. Appreciate your inputs.

Thanks

**Comment by jornfranke** [comment]
There are a couple of things.

1) Can you please create a "fat" jar with all dependencies included (cf. https://stackoverflow.com/questions/16222748/building-a-fat-jar-using-maven). 

2) You seem to be using Java. Can you please try before with the scala version to see if it works in general? 

3) Do you want to have SpreadSheetCells returned or simple datatypes (byte, int etc.)? In the later case you need to activate simpleMode.

4) Microsoft Excel supports maximum 1 Million rows / sheet. The hadoopoffice library and the underlying Apache POI supports more, but this would not be readable in Excel.
Given the data volumes you may need to think about if another format is more suitable - this depends on the analysis that you want to do.  A

5) Do you have some more information on which version of  Spark you have in the Azure Cluster? This version you need to include in the dependencies. Is scala 2.11 or 2.10 enabled? If you have not this information then please try with Spark 2.0.1

6) All options are in String format

7) Junit - we recommend junit 5 jupiter

**Comment by jornfranke** [comment]
Another question: Do you have KyroSerialization activated?

**Comment by jornfranke** [comment]
Could you finally solve your problems?

**Comment by jornfranke** [comment]
issue cannot be reproduced on our side, please open another issue if you still face the problem
