### ISSUE TITLE
enhancement request to return cell value as object rather than string

### ISSUE THREAD

**Issue by candy-hkuk** [ZuInnoTe/hadoopoffice#28]
Following excel parsing, would it be possible to retrieve cell content as object rather than as string.

ie in a similar manner as follows:

public Object getCellContent(XSSFCell cell) {
		switch(cell.getCellTypeEnum()) {
		case BLANK:
			return null;
		case FORMULA:
			break;
		case NUMERIC:
			if(DateUtil.isCellDateFormatted(cell)) {
			    return cell.getDateCellValue();
			} else {
				return cell.getNumericCellValue();
			}
		case BOOLEAN:
			return cell.getBooleanCellValue();
		case STRING:
			return cell.getStringCellValue();
		case ERROR:
		case _NONE:
		default:
			return "error";			
		}
		return null;
	}	

Thanks,

**Comment by jornfranke** [comment]
You can get the cell value as object already using the converter https://github.com/ZuInnoTe/hadoopoffice/wiki/Convert-spreadsheet-cells-to-simple-datatypes-and-vice-versa

**Comment by jornfranke** [comment]
May I ask what Big Data platform do you use ? Hadoop MR? Flink? Spark?

**Comment by candy-hkuk** [comment]
Spark with Ignite.

**Comment by jornfranke** [comment]
Then you can use the converter or the Spark Datasource to have an object

**Comment by jornfranke** [comment]
Did this help you?

**Comment by jornfranke** [comment]
Please create a new issue if the converter does not help you.
