### ISSUE TITLE
Templates and LowFootprint Mode

### ISSUE THREAD

**Issue by rnatarajan** [ZuInnoTe/hadoopoffice#53]
I am facing issues trying to write large dataset using both excel template as well as lowfootprint mode.

From https://github.com/ZuInnoTe/hadoopoffice/wiki/Limitations-of-reading-Excel-files-in-low-footprint-mode I can see that LowFootprint Reading does not support templates.

Does the same apply to using hadoopoffice.write.lowFootprint true and using a template to write xlsx file ?

**Comment by jornfranke** [comment]
Templates are only used during writing and not during reading.

At the moment writing with templates does not support low footprint mode. 
There are more conceptual reasons for that: it is currently difficult to write images and other embedded objects in low footprint mode. Formulas are not calculated in low footprint mode (if you open the file in Excel directly afterwards this might be less of an issue). Formatting information are lost in low footprint mode.
I think those features will requires more deep investigation on how they can be realized (if they can be realize) in low footprint mode.

**Comment by rnatarajan** [comment]
Thanks @jornfranke . That makes Sense.
