### ISSUE TITLE
Pyspark - java.lang.NoSuchMethodError while reading excel file

### ISSUE THREAD

**Issue by mnkumar8** [ZuInnoTe/hadoopoffice#57]
Hi,

I get an error java.lang.NoSuchMethodError while reading excel file from databricks. Please let me know how to fix the error.

My environment:
* I am running the code in databricks. Python: 3.5.2, Spark: 2.4.3. Installed Maven library 'com.github.zuinnote:spark-hadoopoffice-ds_2.12:1.3.3' on my cluster.
* Excel file is stored in Azure blob and I am trying to access it using wasbs path.

My code ('spark' is SparkSession) :
xlDF = spark.read.format("org.zuinnote.spark.office.excel").option("hadoopoffice.read.mimeType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").option("io.file.buffer.size", 64).option("hadoopoffice.read.sheets", "Sheet1").option("read.spark.useHeader", "true").option("hadoopoffice.read.lowFootprint", "true").load(excelFilePath)

Error:
Py4JJavaError                             Traceback (most recent call last)
<command-4234367023720860> in <module>()
xlDF = spark.read.format("org.zuinnote.spark.office.excel").option("hadoopoffice.read.mimeType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").option("io.file.buffer.size", 64).option("hadoopoffice.read.sheets", "Sheet1").option("read.spark.useHeader", "true").option("hadoopoffice.read.lowFootprint", "true").load(excelFilePath)

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o252.load.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.FileFormat.$init$(Lorg/apache/spark/sql/execution/datasources/FileFormat;)V
	at org.zuinnote.spark.office.excel.DefaultSource.<init>(DefaultSource.scala:115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:338)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:283)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

Thanks,
Naveen Kumar

**Comment by jornfranke** [comment]
Hi,

it looks like that you use the wrong scala version of the datasource. Can you please check which scala version is installed on your cluster? Then you can try with scala version 2.11 if 2.11 is installed:
com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.3.3 

please let me know if this works for you.

best regards

**Comment by mnkumar8** [comment]
Thanks for the quick reply. Scala version was 2.11 on my cluster. I installed the corresponding maven library version (com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.3.3) on my cluster and it worked. Thanks.

However, I see an issue with the resultant data and its datatype. I don't see the resultant data in a proper tabular format.
After reading the excel, the type of the resultant dataframe is 
xlDF:pyspark.sql.dataframe.DataFrame = [rows: array] #'xlDF' is the resultant dataframe

xlDF.head(2) - This command gives the below result. 1) It is considering header row as a record inspite of setting 'option("read.spark.useHeader", "true")'. 2) I see metadata for each excel cell.

[Row(rows=[Row(formattedValue='Column1', comment='', formula='', address='A1', sheetName='Sheet1'), Row(formattedValue='Column2', comment='', formula='', address='B1', sheetName='Sheet1'), Row(formattedValue='Column3', comment='', formula='', address='C1', sheetName='Sheet1'), Row(formattedValue='Column4', comment='', formula='', address='D1', sheetName='Sheet1'), Row(formattedValue='Column5', comment='', formula='', address='E1', sheetName='Sheet1')]),
 Row(rows=[Row(formattedValue='Column1_Value1', comment='', formula='', address='A2', sheetName='Sheet1'), Row(formattedValue='Column2_Value1', comment='', formula='', address='B2', sheetName='Sheet1'), Row(formattedValue='Column3_Value1', comment='', formula='', address='C2', sheetName='Sheet1'), Row(formattedValue='Column4_Value1', comment='', formula='', address='D2', sheetName='Sheet1'), Row(formattedValue='Column5_Value1', comment='', formula='', address='E2', sheetName='Sheet1')])]

Expected output (How do I see the expected results?): 
[Row(Column1='Column1_Value1', Column2='Column2_Value1', Column3='Column3_Value1', Column4='Column4_Value1', Column5='Column5_Value1'),
 Row(Column1='Column1_Value2', Column2='Column2_Value2', Column3='Column3_Value2', Column4='Column4_Value2', Column5='Column5_Value2')]

**Comment by jornfranke** [comment]
Yes, the data source has two modes:
1) cell mode (which is what you see), where you have more detailed information about the cell
2) simple mode (activate it via the option read.spark.simpleMode to true). This represents the Excel sheet using primitive datatype and this looks like what you need, see also here: https://github.com/ZuInnoTe/spark-hadoopoffice-ds

**Comment by mnkumar8** [comment]
Thanks Jorn. If I use option 'read.spark.simpleMode', then I am getting the below error.

Code:
xlDF = spark.read.format("org.zuinnote.spark.office.excel").option("read.spark.simpleMode", "true").option("hadoopoffice.read.mimeType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").option("io.file.buffer.size", 64).option("hadoopoffice.read.sheets", "Sheet1").option("read.spark.useHeader", "true").option("hadoopoffice.read.lowFootprint", "true").load(excelFilePath)

Error:
Py4JJavaError                             Traceback (most recent call last)
<command-4234367023720860> in <module>()
----> 1 xlDF = spark.read.format("org.zuinnote.spark.office.excel").option("read.spark.simpleMode", "true").option("hadoopoffice.read.mimeType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").option("io.file.buffer.size", 64).option("hadoopoffice.read.sheets", "Sheet1").option("read.spark.useHeader", "true").option("hadoopoffice.read.lowFootprint", "true").load(excelFilePath)

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o544.load.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.PartitionedFile.<init>(Lorg/apache/spark/sql/catalyst/InternalRow;Ljava/lang/String;JJ[Ljava/lang/String;)V
	at org.zuinnote.spark.office.excel.DefaultSource.inferSchema(DefaultSource.scala:166)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:204)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:195)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:195)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:412)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:283)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jornfranke** [comment]
I cannot reproduce this. This works fine with Spark 2.4.3 here. It looks to me that you still have some scala 2.12 dependencies in your application. How does your build file looks like.

**Comment by jornfranke** [comment]
Can you maybe also tell us how you modified the cluster? how did you deploy the Maven artefact? how do you use Spark-submit? What other Python and Spark dependencies are you using? Is the Pyspark version also the same as the Spark cluster version?

**Comment by jornfranke** [comment]
Could you solve the problem?

**Comment by jornfranke** [comment]
please open a new issue if the problem still persists
