### ISSUE TITLE
config "dateTimePattern" is not working

### ISSUE THREAD

**Issue by dohongdayi** [ZuInnoTe/hadoopoffice#63]
https://github.com/ZuInnoTe/hadoopoffice/blob/29557b613fdf53de4a76ff7ccfda577cc2ac2107/fileformat/src/main/java/org/zuinnote/hadoop/office/format/common/HadoopOfficeWriteConfiguration.java#L401

above shoud be changed to "this.setSimpleDateTimeFormat(...)", or config "hadoopoffice.write.simple.dateTimePattern" is not working.

**Comment by jornfranke** [comment]
thanks for catching this. will be fixed in the next version
