### ISSUE TITLE
Update to Apache PO 5.0.0

### ISSUE THREAD

**Issue by jornfranke** [ZuInnoTe/hadoopoffice#66]
Update to Apache PO 5.0.0, once it is out. 
https://poi.apache.org/changes.html#5.0.0

Most relevant for Excel processing are updated dependencies

**Comment by pjfanning** [comment]
@jornfranke POI 5.0.0 is released

**Comment by jornfranke** [comment]
Cool thanks! I will check this week to get it integrated.

**Comment by jornfranke** [comment]
will take a week more, upgrading also Hadoop, Hive, Flink and Spark

**Comment by jornfranke** [comment]
supported with release 1.4
