### ISSUE TITLE
Error usign hadoopoffice in google colab

### ISSUE THREAD

**Issue by tatimm84** [ZuInnoTe/hadoopoffice#67]
Hi,
I am trying to use hadoopoffice at google colab, but is not working. Can anyone help, please?
I am using the following code with their outputs:

1 # Install depedencies of pyspark
2 !apt-get install openjdk-8-jdk-headless -qq > /dev/null
3 !wget -q https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
4 !tar xf spark-2.4.4-bin-hadoop2.7.tgz
5 !pip install -q findspark
6 # Install hadoopoffice and dropbox
7!git clone https://github.com/ZuInnoTe/hadoopoffice.git hadoopoffice
8!pip install dropbox
9!ls
Cloning into 'hadoopoffice'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 31906 (delta 37), reused 95 (delta 25), pack-reused 31791
Receiving objects: 100% (31906/31906), 7.61 MiB | 20.50 MiB/s, done.
Resolving deltas: 100% (20518/20518), done.
Collecting dropbox
  Downloading https://files.pythonhosted.org/packages/a0/86/5ea3466089883b0c3caff0b314ffc1b98c96f417e26903292b4a1e40342c/dropbox-10.2.0-py3-none-any.whl (668kB)
     |████████████████████████████████| 675kB 3.5MB/s 
Requirement already satisfied: requests>=2.16.2 in /usr/local/lib/python3.6/dist-packages (from dropbox) (2.23.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from dropbox) (1.12.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.16.2->dropbox) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.16.2->dropbox) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.16.2->dropbox) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.16.2->dropbox) (2.9)
Installing collected packages: dropbox
Successfully installed dropbox-10.2.0
hadoopoffice  spark-2.4.4-bin-hadoop2.7      spark-2.4.4-bin-hadoop2.7.tgz.1
sample_data   spark-2.4.4-bin-hadoop2.7.tgz

1 import os
2 os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
3 os.environ["SPARK_HOME"] = "/content/spark-2.4.4-bin-hadoop2.7"
4 import findspark
5 findspark.init()
6 import pyspark
7 from pyspark.sql import SparkSession
8 from pyspark.sql import Window
9 from pyspark.sql.functions import *
10 spark = SparkSession.builder.master('local[*]').getOrCreate()
11 sc = pyspark.SparkContext.getOrCreate()
12 sql = pyspark.SQLContext(sc)
13 spark = pyspark.sql.SparkSession(sc)
14 findspark.find()
'/content/spark-2.4.4-bin-hadoop2.7'

1 # Imports and initialization of variables
2 import pandas as pd
3 from contextlib import closing # this will correctly close the request
4 import io
5 import dropbox

6 access_token = '' #get token on https://www.dropbox.com/developers/apps/
7 dbx = dropbox.Dropbox(access_token)
8 yourpath = '/BaseDados/Arquivos xls/CFBM_tbBiomedicos.xlsx'
9 # Relevant streamer
10 def stream_dropbox_file(path):
11    _,res=dbx.files_download(path)
12    with closing(res) as result:
13        byte_data=result.content
14        return io.BytesIO(byte_data)
15 # Usage
16 file_stream=stream_dropbox_file(yourpath)
17 #pd.read_excel(file_stream)
18 df = spark.read.format('org.zuinnote.spark.office.excel').load(file_stream)
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-6-2e855d55c812> in <module>()
     22 file_stream=stream_dropbox_file(yourpath)
     23 #pd.read_excel(file_stream)
---> 24 df = spark.read.format('org.zuinnote.spark.office.excel').load(file_stream)

3 frames
/content/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    168             if type(path) != list:
    169                 path = [path]
--> 170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
    172             return self._df(self._jreader.load())

/content/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/content/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/content/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o51.load.
: java.lang.ClassNotFoundException: Failed to find data source: org.zuinnote.spark.office.excel. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.zuinnote.spark.office.excel.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
	at scala.util.Try.orElse(Try.scala:84)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:634)
	... 12 more

**Comment by jornfranke** [comment]
Upps, sorry I overlooked this issue :(
For Python you need to add the .jar to the Spark Classpath (of Executor and Driver). You can put it locally or on a blob storage (e.g. Google Cloud Storage, S3 etc.).
Please set programmatically the following options in the Spark: spark.driver.extraClassPath, spark.executor.extraClassPath.
Check also here: https://spark.apache.org/docs/latest/configuration.html

Maybe I will create a Python package on pypi that helps a bit dealing with this by using simply pip install.

**Comment by jornfranke** [comment]
closed as no further feedback. If issue persists with the latest version of hadoopoffice then please create a new issue
