### ISSUE TITLE
Unable to read old xls file using org.zuinnote.spark.office.excel 

### ISSUE THREAD

**Issue by shilpa-parimi** [ZuInnoTe/hadoopoffice#68]
Hi Guys,
SO I have a file in old xls format(Microsoft Excel 97-2003 Worksheet (.xls)). I am unable to read this with com.crealytics.spark.excel.
SO I have read somewhere we can do that with org.zuinnote.spark.office.excel. But Iam getting Error as follows.
Can anyone help me regarding this. Iam struck here since long
val file="local\\new.xls"
**Code**:
  val hfdf=spark.read
      .format("org.zuinnote.spark.office.excel")
      .option("read.locale.bcp47", "de")
      .option("read.spark.simpleMode",true)
   .option("hadoopoffice.read.sheet.skiplines.allsheets",19)
      .load(file)
    hfdf.show(10,false)
**Error**
2020-06-25 15:54:16,308 ERROR [main] mapreduce.AbstractSpreadSheetDocumentRecordReader (AbstractSpreadSheetDocumentRecordReader.java:initialize(211)) - org.zuinnote.hadoop.office.format.common.parser.FormatNotUnderstoodException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
2020-06-25 15:54:19,721 ERROR [Executor task launch worker for task 0] mapreduce.AbstractSpreadSheetDocumentRecordReader (AbstractSpreadSheetDocumentRecordReader.java:initialize(211)) - org.zuinnote.hadoop.office.format.common.parser.FormatNotUnderstoodException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
++
||
++
++

**Comment by jornfranke** [comment]
Are you sure it is the right format ?
Can you open it in Excel?

Is it encrypted? (Password protected ?)

**Comment by shilpa-parimi** [comment]
Iam getting this dialog while opening.
**The file format and extension of 'file.xls' dont match. The file could be corrupted or unsafe. Unless you trust its source. don't open it Do you want to open it anyway?**
when I click yes I am able to open it.(I thought it is happening because of old format)

And one more than thing. When I tried to copy it in other xls ,I am able to read as df but while opening I am getting the same error.

**Comment by jornfranke** [comment]
It seems the file is corrupt. Try to save it into as a new file and try again. It seems that the file cannot be recovered directly in HadoopOffice

**Comment by shilpa-parimi** [comment]
Okay When I will check on how to recover it. and also I wanted to skip first few lines of xl while reading Iam using below lines. but it is not working ,  Can you help where am I doing wrong?
    val hfdf=spark.read
      .format("org.zuinnote.spark.office.excel")
      .option("read.locale.bcp47", "us")
      .option("read.spark.simpleMode",true)

   .option("hadoopoffice.read.sheet.skiplines.num",19)

    .option("hadoopoffice.read.sheet.skiplines.allsheets","true").option("hadoopoffice.read.sheets","dilosk3_custom_ndilosk3-462674_")

**Comment by jornfranke** [comment]
This should work.

**Comment by jornfranke** [comment]
Did it work out for you?

**Comment by jornfranke** [comment]
Check out the latest version and also note that the config options have changed in the latest version. If it still not works then please create a new issue
